# ============================================
# HRM - Docker Environment Setup
# Run from project root: .\scripts\setup-docker.ps1
# ============================================

$ErrorActionPreference = "Stop"

$ProjectRoot = Split-Path -Parent (Split-Path -Parent $PSScriptRoot)
Set-Location $ProjectRoot

Write-Host "============================================"
Write-Host "  HRM - Docker Environment Setup"
Write-Host "============================================"

# --- 1. Check prerequisites ---
Write-Host ""
Write-Host "[1/5] Checking prerequisites..."

try {
    $dockerVer = docker -v
} catch {
    Write-Host "ERROR: Docker not found. Install from https://docs.docker.com/get-docker/"
    exit 1
}

try {
    $composeVer = docker compose version 2>$null
    if (-not $composeVer) { $composeVer = docker-compose -v }
} catch {
    Write-Host "ERROR: Docker Compose not found."
    exit 1
}

Write-Host "  Docker: $dockerVer"

# --- 2. Root .env for Docker ---
Write-Host ""
Write-Host "[2/5] Configuring Docker environment..."
$RootEnv = Join-Path $ProjectRoot ".env"
if (-not (Test-Path $RootEnv)) {
    $bytes = New-Object byte[] 32
    [System.Security.Cryptography.RandomNumberGenerator]::Create().GetBytes($bytes)
    $jwtSecret = [Convert]::ToBase64String($bytes)
    @"
# HRM Docker - generated by setup-docker.ps1
JWT_SECRET=$jwtSecret
JWT_EXPIRES_IN=7d
BACKEND_PORT=5000
FRONTEND_PORT=80
"@ | Set-Content $RootEnv -Encoding UTF8
    Write-Host "  Created .env with random JWT_SECRET"
} else {
    Write-Host "  .env already exists"
    if ((Get-Content $RootEnv -Raw) -match "change_me") {
        Write-Host "  WARN: Update JWT_SECRET in .env for production!"
    }
}

# --- 3. Build images ---
Write-Host ""
Write-Host "[3/5] Building Docker images..."
docker compose build

# --- 4. Start containers ---
Write-Host ""
Write-Host "[4/5] Starting containers..."
docker compose up -d

# --- 5. Wait for backend, then seed ---
Write-Host ""
Write-Host "[5/5] Waiting for backend and seeding..."
Start-Sleep -Seconds 5
$seeded = $false
for ($i = 1; $i -le 10; $i++) {
    try {
        docker exec hrm-backend npx prisma db push --accept-data-loss 2>$null
        docker exec hrm-backend npm run seed:prod 2>$null
        Write-Host "  Seed complete. Default admin: admin@hrm.com / admin123"
        $seeded = $true
        break
    } catch {
        Write-Host "  Waiting for backend... ($i/10)"
        Start-Sleep -Seconds 3
    }
}
if (-not $seeded) {
    Write-Host "  Seed skipped. Run manually: docker exec hrm-backend npm run seed:prod"
}

# --- Done ---
Write-Host ""
Write-Host "============================================"
Write-Host "  Docker setup complete!"
Write-Host "============================================"
Write-Host ""
Write-Host "  Frontend: http://localhost (or http://localhost:80)"
Write-Host "  Backend:  http://localhost:5000"
Write-Host ""
Write-Host "Commands:"
Write-Host "  docker compose logs -f   # View logs"
Write-Host "  docker compose down      # Stop"
Write-Host ""
Write-Host "Default admin (if seeded): admin@hrm.com / admin123"
Write-Host ""
