#!/bin/bash
# ============================================
# HRM - Docker Environment Setup
# Run from project root: ./scripts/setup-docker.sh
# ============================================

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$PROJECT_ROOT"

echo "============================================"
echo "  HRM - Docker Environment Setup"
echo "============================================"

# --- 1. Check prerequisites ---
echo ""
echo "[1/5] Checking prerequisites..."

if ! command -v docker &>/dev/null; then
  echo "ERROR: Docker not found. Install from https://docs.docker.com/get-docker/"
  exit 1
fi

if ! docker compose version &>/dev/null && ! docker-compose version &>/dev/null; then
  echo "ERROR: Docker Compose not found. Install Docker Desktop or docker-compose."
  exit 1
fi

echo "  Docker: $(docker -v)"
echo "  Compose: $(docker compose version 2>/dev/null || docker-compose -v)"

# --- 2. Root .env for Docker ---
echo ""
echo "[2/5] Configuring Docker environment..."
ROOT_ENV="$PROJECT_ROOT/.env"
if [ ! -f "$ROOT_ENV" ]; then
  JWT_SECRET=$(openssl rand -base64 32 2>/dev/null || echo "change_me_to_strong_secret_32chars_min")
  cat > "$ROOT_ENV" << EOF
# HRM Docker - generated by setup-docker.sh
JWT_SECRET=$JWT_SECRET
JWT_EXPIRES_IN=7d
BACKEND_PORT=5000
FRONTEND_PORT=80
EOF
  echo "  Created .env with random JWT_SECRET"
else
  echo "  .env already exists"
  if grep -q "change_me" "$ROOT_ENV" 2>/dev/null; then
    echo "  WARN: Update JWT_SECRET in .env for production!"
  fi
fi

# --- 3. Build images ---
echo ""
echo "[3/5] Building Docker images..."
docker compose build

# --- 4. Start containers ---
echo ""
echo "[4/5] Starting containers..."
docker compose up -d

# --- 5. Wait for backend, then seed ---
echo ""
echo "[5/5] Waiting for backend and seeding..."
sleep 5
for i in 1 2 3 4 5 6 7 8 9 10; do
  if docker exec hrm-backend npx prisma db push --accept-data-loss 2>/dev/null; then
    break
  fi
  echo "  Waiting for backend... ($i/10)"
  sleep 3
done

if docker exec hrm-backend npm run seed:prod 2>/dev/null; then
  echo "  Seed complete. Default admin: admin@hrm.com / admin123"
else
  echo "  Seed skipped (may already have data)"
fi

# --- Done ---
echo ""
echo "============================================"
echo "  Docker setup complete!"
echo "============================================"
echo ""
echo "  Frontend: http://localhost (or http://localhost:80)"
echo "  Backend:  http://localhost:5000"
echo ""
echo "Commands:"
echo "  docker compose logs -f   # View logs"
echo "  docker compose down      # Stop"
echo ""
echo "Default admin (if seeded): admin@hrm.com / admin123"
echo ""
